### ISSUE TITLE
Rendering of mana costs

### ISSUE THREAD

**Issue by mmoroney01** [bdwlyon/mtg-rnn-sort#8]
Card's mana cost will occasionally render as _nocost_ if CMC = 0, has rendered {2U} instead of proper mana symbols

**Comment by bdwlyon** [comment]
Probably going to leave `_NOCOST_` as it is distinct from {0}, and lets you know that the card actually doesn't have a cost rather than something just getting messed up somewhere. I think that {2U} is a mistake on the part of the RNN (rather than the card renderer), properly formatted mana cost should be {2}{U}.
